### ISSUE TITLE
Kepler.gl Geoview, Geospatial View and Geospatial View static do not work with geometric columns that are not named "geometry"

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#22]
To reproduce create a KNIME table with a Geo column with name column1. Select this column to visualize it in the Kepler.gl view node and you will get the following exception:
`WARN  Kepler.gl Geoview    3:117      Traceback (most recent call last):
  File "C:\KNIME\NIGHTLY\knime_nightly\plugins\org.knime.python3.nodes_4.7.0.v202210281512\src\main\python\knime_node_backend.py", line 470, in execute
    outputs = self._node.execute(exec_context, *inputs)
  File "C:\DEV\GIT\EXTERNAL\knime-geospatial-extension\knime_extension\src\nodes\visualize.py", line 865, in execute
    map_1.add_data(data=gdf.copy(), name="state")
  File "C:\Users\Tobias\.conda\envs\geospatial_env\lib\site-packages\keplergl\keplergl.py", line 140, in add_data
    normalized = _normalize_data(data)
  File "C:\Users\Tobias\.conda\envs\geospatial_env\lib\site-packages\keplergl\keplergl.py", line 50, in _normalize_data
    return _gdf_to_dict(data) if isinstance(data, geopandas.GeoDataFrame) else _df_to_dict(data)
  File "C:\Users\Tobias\.conda\envs\geospatial_env\lib\site-packages\keplergl\keplergl.py", line 44, in _gdf_to_dict
    df[name] = df.geometry.apply(lambda x: shapely.wkt.dumps(x))
  File "C:\Users\Tobias\.conda\envs\geospatial_env\lib\site-packages\pandas\core\generic.py", line 5907, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'geometry'
`

**Comment by wybert** [comment]
Fixed
