### ISSUE TITLE
Geospatial View Static node throws exception if "Marker color column" is not selected

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#23]
To reproduce use an input table with a single Geo column. Execute the node as it is predefined (e.g. Geometry column is the input column and Marker color column is empty). Do not select None in the Marker column select box. This results in the following error:
`WARN  Geospatial View Static 3:119      Traceback (most recent call last):
  File "C:\KNIME\NIGHTLY\knime_nightly\plugins\org.knime.python3.nodes_4.7.0.v202210281512\src\main\python\knime_node_backend.py", line 470, in execute
    outputs = self._node.execute(exec_context, *inputs)
  File "C:\DEV\GIT\EXTERNAL\knime-geospatial-extension\knime_extension\src\nodes\visualize.py", line 721, in execute
    self.legend_caption = self.color_col
  File "C:\KNIME\NIGHTLY\knime_nightly\plugins\org.knime.python3.nodes_4.7.0.v202210281512\src\main\python\knime_parameter.py", line 426, in __set__
    self._validate(value)
  File "C:\KNIME\NIGHTLY\knime_nightly\plugins\org.knime.python3.nodes_4.7.0.v202210281512\src\main\python\knime_parameter.py", line 435, in _validate
    self._validator(value)
  File "C:\KNIME\NIGHTLY\knime_nightly\plugins\org.knime.python3.nodes_4.7.0.v202210281512\src\main\python\knime_parameter.py", line 652, in default_validator
    raise TypeError(
TypeError: None is of type <class 'NoneType'>, but should be of type string.`

**Comment by wybert** [comment]
fxied
